package astt.una.prograiv.sistema.domain;
// Generated 27/09/2017 02:51:11 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Chofer generated by hbm2java
 */
public class Chofer  implements java.io.Serializable {


     private String cedula;
     private String tipolicencia;
     private Date fechanacimiento;
     private Date vencimientolicencia;
     private Date fecha;
     private String usuario;
     private boolean activo;
    public Chofer() {
    }

	
    public Chofer(String cedula, String tipolicencia, Date fechanacimiento, Date vencimientolicencia,boolean activo) {
        this.cedula = cedula;
        this.tipolicencia = tipolicencia;
        this.fechanacimiento = fechanacimiento;
        this.vencimientolicencia = vencimientolicencia;
        this.activo = activo;
    }
    public Chofer(String cedula, String tipolicencia, Date fechanacimiento, Date vencimientolicencia,boolean activo, Date fecha, String usuario) {
       this.cedula = cedula;
       this.tipolicencia = tipolicencia;
       this.fechanacimiento = fechanacimiento;
       this.vencimientolicencia = vencimientolicencia;
       this.fecha = fecha;
       this.usuario = usuario;
       this.activo = activo;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getTipolicencia() {
        return this.tipolicencia;
    }
    
    public void setTipolicencia(String tipolicencia) {
        this.tipolicencia = tipolicencia;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public Date getVencimientolicencia() {
        return this.vencimientolicencia;
    }
    
    public void setVencimientolicencia(Date vencimientolicencia) {
        this.vencimientolicencia = vencimientolicencia;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public boolean isActivo() {
        return activo;
    }

    public void setActivo(boolean activo) {
        this.activo = activo;
    }


}


