package astt.una.prograiv.sistema.domain;
// Generated 27/09/2017 02:51:11 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Chofervehiculo generated by hbm2java
 */
public class Chofervehiculo  implements java.io.Serializable {


     private int idchofervehiculo;
     private String cedulachofer;
     private String idvehiculo;
     private boolean activo;
     private Date fecha;
     private String usuario;

    public Chofervehiculo() {
    }

	
    public Chofervehiculo(int idchofervehiculo, String cedulachofer, String idvehiculo,boolean activo) {
        this.idchofervehiculo = idchofervehiculo;
        this.cedulachofer = cedulachofer;
        this.idvehiculo = idvehiculo;
        this.activo = activo;
        
    }
    public Chofervehiculo(int idchofervehiculo, String cedulachofer, String idvehiculo,boolean activo, Date fecha, String usuario) {
       this.idchofervehiculo = idchofervehiculo;
       this.cedulachofer = cedulachofer;
       this.idvehiculo = idvehiculo;
        this.activo = activo;
       this.fecha = fecha;
       this.usuario = usuario;
    }
   
    public int getIdchofervehiculo() {
        return this.idchofervehiculo;
    }
    
    public void setIdchofervehiculo(int idchofervehiculo) {
        this.idchofervehiculo = idchofervehiculo;
    }
    public String getCedulachofer() {
        return this.cedulachofer;
    }
    
    public void setCedulachofer(String cedulachofer) {
        this.cedulachofer = cedulachofer;
    }
    public String getIdvehiculo() {
        return this.idvehiculo;
    }
    
    public void setIdvehiculo(String idvehiculo) {
        this.idvehiculo = idvehiculo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getUsuario() {
        return this.usuario;
    }

    public boolean isActivo() {
        return activo;
    }

    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
}


