package astt.una.prograiv.sistema.domain;
// Generated 27/09/2017 02:51:11 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private String idVehiculo;
     private String duenno;
     private Date anno;
     private String modelo;
     private String placa;
     private String color;
     private int puntuacion;
     private boolean estado;
     private boolean activo;
     private String ubicacionActual;
     private Date fecha;
     private String usuario;
     

    public Vehiculo() {
    }

	
    public Vehiculo(String idVehiculo,String duenno, Date anno, String modelo, String placa, String color, int puntuacion, boolean estado, boolean activo ,String ubicacionActual) {
        this.idVehiculo = idVehiculo;
        this.duenno=duenno;
        this.anno = anno;
        this.modelo = modelo;
        this.placa = placa;
        this.color = color;
        this.puntuacion = puntuacion;
        this.estado = estado;
        this.activo = activo;
        this.ubicacionActual = ubicacionActual;
    }
    public Vehiculo(String idVehiculo, String duenno, Date anno, String modelo, String placa, String color, int puntuacion, boolean estado, boolean activo, String ubicacionActual, Date fecha, String usuario) {
       this.idVehiculo = idVehiculo;
       this.duenno = duenno;
       this.anno = anno;
       this.modelo = modelo;
       this.placa = placa;
       this.color = color;
       this.puntuacion = puntuacion;
       this.estado = estado;
       this.activo = activo;
       this.ubicacionActual = ubicacionActual;
       this.fecha = fecha;
       this.usuario = usuario;
     
    }
   
    public String getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(String idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public String getDuenno() {
        return this.duenno;
    }
    
    public void setDuenno(String duenno) {
        this.duenno = duenno;
    }
    public Date getAnno() {
        return this.anno;
    }
    
    public void setAnno(Date anno) {
        this.anno = anno;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public int getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(int puntuacion) {
        this.puntuacion = puntuacion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }

    public String getUbicacionActual() {
        return ubicacionActual;
    }

    public void setUbicacionActual(String ubicacionActual) {
        this.ubicacionActual = ubicacionActual;
    }
   
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getUsuario(){
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario= usuario;
    }
    



}


